name: Build
on:
  push:
    branches:
    - master
jobs:
  build:
    runs-on: ubuntu-latest
    container: quay.io/fedora/fedora:35-x86_64
    steps:
    - uses: actions/checkout@v3
    - run: cat /etc/redhat-release
    - run: ls
    - run: pwd
