name: Build
on:
  push:
    branches:
    - master
env:
  VERSION: 99.0.4844.82-1
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    container: quay.io/fedora/fedora:35-x86_64
    steps:
    - uses: actions/checkout@v3
    - name: build
      run: |
        echo ## Install tools
        dnf install -y rpmdevtools wget dnf-plugin-builddep
        echo ## Setup tree
        rpmdev-setuptree
        cp ungoogled-chromium.spec ~/rpmbuild/SPECS/
        cp -r * ~/rpmbuild/SOURCES/
        pushd ~/rpmbuild/
        pushd SOURCES/
        wget https://github.com/Eloston/ungoogled-chromium/archive/${VERSION}/ungoogled-chromium-${VERSION}.tar.gz
        wget https://chromium.googlesource.com/chromium/tools/depot_tools/+archive/a8c66d0dabec812f47b6f2a4639baca46b9b4d7a.tar.gz
        mv a8c66d0dabec812f47b6f2a4639baca46b9b4d7a.tar.gz depot_tools-a8c66d0dabec812f47b6f2a4639baca46b9b4d7a.tar.gz
        gunzip depot_tools-a8c66d0dabec812f47b6f2a4639baca46b9b4d7a.tar.gz
        xz depot_tools-a8c66d0dabec812f47b6f2a4639baca46b9b4d7a.tar
        wget https://www.x.org/releases/individual/proto/xcb-proto-1.14.tar.xz
        popd
        echo ## Tree ready
        find
        echo ## Install buildeps
        dnf builddep -y  SPECS/ungoogled-chromium.spec
        echo ## Do build
        rpmbuild -bb --undefine=_disable_source_fetch SPECS/ungoogled-chromium.spec
        popd
    - uses: actions/upload-artifact@v3
      with:
        name: rpm
        path: ~/rpmbuild/RPMS/*
